window.PORTFOLIO_DATA = {
  en: {
    meta: {
      title: "Lev Levinov | Engineering Portfolio",
      description:
        "Bilingual engineering portfolio for Lev Levinov: electronics, embedded systems, CAD, prototyping and digital fabrication.",
    },
    navigation: {
      profile: "Profile",
      experience: "Experience",
      skills: "Skills",
      projects: "Projects",
      education: "Education",
      contact: "Contact",
    },
    translations: {
      current: "Current position",
      viewProjects: "View Projects",
      contact: "Contact",
      downloadCv: "Download CV",
      viewDetails: "View details",
      learnMore: "Learn more",
      responsibilities: "Key responsibilities",
      skillsUsed: "Skills used",
      tools: "Tools & Technologies",
      status: "Project status",
      context: "Context",
      objective: "Objective",
      technicalApproach: "Technical approach",
      result: "Result",
      skillsDemonstrated: "Skills demonstrated",
      gallery: "Gallery / images area",
      contextCompany: "Context and company",
      technicalTasks: "Technical tasks",
      resultsImpact: "Results and impact",
      all: "All",
      backToProjects: "Back to projects",
      backToExperience: "Back to experience",
      toBeCompleted: "To be completed",
      menuOpen: "Open navigation",
      menuClose: "Close navigation",
    },
    hero: {
      title: "Lev Levinov",
      subtitle: "Engineering portfolio - electronics, embedded systems and digital fabrication",
      positioning: "Electronics, embedded systems, CAD, prototyping, digital fabrication.",
      locationLabel: "Location",
      location: "France - Bordeaux / Ardeche",
      availabilityLabel: "Availability",
      availability: "Technical projects, internships, collaborations and professional opportunities",
      cvHref: "#",
      photoSrc: "/public/images/profile-photo.png",
      photoAlt: "Professional portrait of Lev Levinov",
    },
    profile: {
      eyebrow: "Profile",
      title: "Technical profile focused on precise, testable engineering work.",
      description: [
        "Lev Levinov is building a professional path around electronics, embedded systems, CAD, prototyping and digital fabrication.",
        "This portfolio is structured to document verified experience, technical projects, education and future certifications without overstating unconfirmed details.",
        "The technical focus is practical: understand constraints, design clean solutions, prototype carefully and document results for future iteration.",
      ],
      qualities: ["Autonomous", "Rigorous", "Solution-oriented"],
    },
    currentPosition: {
      eyebrow: "Current position",
      title: "Current technical direction",
      status: "Current training or work status: To be completed.",
      areas: ["Electronics", "Embedded systems", "Prototyping", "CAD", "Digital fabrication"],
    },
    skills: {
      eyebrow: "Skills",
      title: "Competencies organized by technical domain.",
      categories: [
        {
          title: "Electronics & Embedded Systems",
          items: ["Circuit analysis", "Sensors and actuators", "Microcontrollers", "Signal basics", "Testing and troubleshooting"],
        },
        {
          title: "CAD & Mechanical Design",
          items: ["Parametric modeling", "Mechanical assemblies", "Technical drawings", "Design for manufacturing", "Tolerance awareness"],
        },
        {
          title: "Digital Fabrication: 3D Printing & CNC",
          items: ["FDM 3D printing", "CNC milling principles", "Material constraints", "Prototype iteration", "Workshop preparation"],
        },
        {
          title: "Programming & Technical Tools",
          items: ["Structured technical documentation", "Version control basics", "Automation mindset", "Data sheets", "Debugging workflow"],
        },
      ],
    },
    experience: {
      eyebrow: "Experience",
      title: "Professional experience",
      items: [
        {
          slug: "technical-experience-placeholder",
          title: "Technical experience",
          company: "Company or context: To be completed",
          period: "Period: To be completed",
          location: "Location: To be completed",
          summary:
            "Placeholder entry for verified professional experience. Replace with a real role, company or project context when confirmed.",
          responsibilities: ["To be completed", "To be completed", "To be completed"],
          skills: ["Technical documentation", "Problem solving", "Engineering workflow"],
          details: {
            context: "Company, team, project scope and operating context: To be completed.",
            technicalTasks: ["To be completed", "To be completed", "To be completed"],
            results: ["To be completed", "To be completed"],
          },
        },
      ],
    },
    projects: {
      eyebrow: "Projects",
      title: "Technical projects and case studies",
      filters: [
        { key: "all", label: "All" },
        { key: "electronics", label: "Electronics" },
        { key: "drones", label: "Drones" },
        { key: "cad", label: "CAD" },
        { key: "cnc", label: "CNC" },
        { key: "3d-printing", label: "3D Printing" },
        { key: "personal-rd", label: "Personal R&D" },
      ],
      items: [
        {
          slug: "embedded-electronics-prototype",
          title: "Embedded electronics prototype",
          category: "Electronics",
          filter: "electronics",
          summary:
            "Placeholder project for an electronics or embedded systems prototype. Replace with verified scope, components, constraints and test results.",
          tools: ["Microcontroller", "Sensors", "Test equipment", "Technical documentation"],
          status: "To be completed",
          subtitle: "Electronics and embedded systems prototype",
          details: {
            context: "To be completed.",
            objective: "To be completed.",
            approach: "To be completed.",
            result: "To be completed.",
            skills: ["Electronics", "Embedded systems", "Troubleshooting", "Documentation"],
          },
        },
        {
          slug: "cad-digital-fabrication-study",
          title: "CAD and digital fabrication study",
          category: "CAD",
          filter: "cad",
          summary:
            "Placeholder project for a mechanical design, 3D printing or CNC workflow. Replace with real models, materials, tolerances and fabrication output.",
          tools: ["CAD", "3D printing", "CNC workflow", "Measurement"],
          status: "To be completed",
          subtitle: "Mechanical design and fabrication workflow",
          details: {
            context: "To be completed.",
            objective: "To be completed.",
            approach: "To be completed.",
            result: "To be completed.",
            skills: ["CAD", "Design for manufacturing", "Prototype iteration", "Technical documentation"],
          },
        },
      ],
    },
    education: {
      eyebrow: "Education & Certifications",
      title: "Education, courses and certifications",
      groups: [
        {
          title: "Diplomas",
          items: [
            {
              name: "To be completed",
              organization: "Organization: To be completed",
              year: "Year: To be completed",
              location: "Location: To be completed",
              competencies: "Key competencies: To be completed",
            },
          ],
        },
        {
          title: "Courses",
          items: [
            {
              name: "To be completed",
              organization: "Organization: To be completed",
              year: "Year: To be completed",
              location: "Location: To be completed",
              competencies: "Key competencies: To be completed",
            },
          ],
        },
        {
          title: "Certifications",
          items: [
            {
              name: "To be completed",
              organization: "Organization: To be completed",
              year: "Year: To be completed",
              location: "Location: To be completed",
              competencies: "Key competencies: To be completed",
            },
          ],
        },
      ],
    },
    contact: {
      eyebrow: "Contact",
      title: "Available for technical projects, internships, collaborations or professional opportunities.",
      location: "France - Bordeaux / Ardeche",
      email: "To be completed",
      phone: "To be completed",
      linkedin: "To be completed",
      github: "https://github.com/levlevinov",
      websites: ["To be completed"],
    },
    footer: {
      label: "Electronics, embedded systems, CAD and digital fabrication",
      copyright: "Copyright 2026 Lev Levinov",
    },
  },
  fr: {
    meta: {
      title: "Lev Levinov | Portfolio d'ingenierie",
      description:
        "Portfolio bilingue d'ingenierie de Lev Levinov : electronique, systemes embarques, CAO, prototypage et fabrication numerique.",
    },
    navigation: {
      profile: "Profil",
      experience: "Experience",
      skills: "Competences",
      projects: "Projets",
      education: "Formation",
      contact: "Contact",
    },
    translations: {
      current: "Situation actuelle",
      viewProjects: "Voir les projets",
      contact: "Me contacter",
      downloadCv: "Telecharger le CV",
      viewDetails: "Voir details",
      learnMore: "En savoir plus",
      responsibilities: "Principales responsabilites",
      skillsUsed: "Competences utilisees",
      tools: "Outils et technologies",
      status: "Statut du projet",
      context: "Contexte",
      objective: "Objectif",
      technicalApproach: "Approche technique",
      result: "Resultat",
      skillsDemonstrated: "Competences demontrees",
      gallery: "Galerie / zone images",
      contextCompany: "Contexte et entreprise",
      technicalTasks: "Taches techniques",
      resultsImpact: "Resultats et impact",
      all: "Tous",
      backToProjects: "Retour aux projets",
      backToExperience: "Retour a l'experience",
      toBeCompleted: "A completer",
      menuOpen: "Ouvrir la navigation",
      menuClose: "Fermer la navigation",
    },
    hero: {
      title: "Lev Levinov",
      subtitle: "Portfolio d'ingenierie - electronique, systemes embarques et fabrication numerique",
      positioning: "Electronique, systemes embarques, CAO, prototypage, fabrication numerique.",
      locationLabel: "Localisation",
      location: "France - Bordeaux / Ardeche",
      availabilityLabel: "Disponibilite",
      availability: "Projets techniques, stages, collaborations et opportunites professionnelles",
      cvHref: "#",
      photoSrc: "/public/images/profile-photo.png",
      photoAlt: "Portrait professionnel de Lev Levinov",
    },
    profile: {
      eyebrow: "Profil",
      title: "Profil technique oriente vers un travail d'ingenierie precis et verifiable.",
      description: [
        "Lev Levinov construit un parcours professionnel autour de l'electronique, des systemes embarques, de la CAO, du prototypage et de la fabrication numerique.",
        "Ce portfolio est structure pour documenter l'experience verifiee, les projets techniques, la formation et les futures certifications sans ajouter d'informations non confirmees.",
        "L'orientation technique est pratique : comprendre les contraintes, concevoir des solutions propres, prototyper avec rigueur et documenter les resultats.",
      ],
      qualities: ["Autonome", "Rigoureux", "Oriente solution"],
    },
    currentPosition: {
      eyebrow: "Situation actuelle",
      title: "Orientation technique actuelle",
      status: "Statut actuel de formation ou de travail : A completer.",
      areas: ["Electronique", "Systemes embarques", "Prototypage", "CAO", "Fabrication numerique"],
    },
    skills: {
      eyebrow: "Competences",
      title: "Competences organisees par domaine technique.",
      categories: [
        {
          title: "Electronique & Systemes embarques",
          items: ["Analyse de circuits", "Capteurs et actionneurs", "Microcontroleurs", "Bases du signal", "Tests et diagnostic"],
        },
        {
          title: "CAO & Conception mecanique",
          items: ["Modelisation parametrique", "Assemblages mecaniques", "Plans techniques", "Conception pour fabrication", "Notions de tolerances"],
        },
        {
          title: "Fabrication numerique : impression 3D & CNC",
          items: ["Impression 3D FDM", "Principes du fraisage CNC", "Contraintes materiaux", "Iteration de prototypes", "Preparation atelier"],
        },
        {
          title: "Programmation & Outils techniques",
          items: ["Documentation technique structuree", "Bases du versioning", "Automatisation", "Fiches techniques", "Methodes de debogage"],
        },
      ],
    },
    experience: {
      eyebrow: "Experience",
      title: "Experience professionnelle",
      items: [
        {
          slug: "technical-experience-placeholder",
          title: "Experience technique",
          company: "Entreprise ou contexte : A completer",
          period: "Periode : A completer",
          location: "Localisation : A completer",
          summary:
            "Entree provisoire pour une experience professionnelle verifiee. Remplacer par un poste, une entreprise ou un contexte projet confirme.",
          responsibilities: ["A completer", "A completer", "A completer"],
          skills: ["Documentation technique", "Resolution de problemes", "Workflow d'ingenierie"],
          details: {
            context: "Entreprise, equipe, perimetre projet et contexte operationnel : A completer.",
            technicalTasks: ["A completer", "A completer", "A completer"],
            results: ["A completer", "A completer"],
          },
        },
      ],
    },
    projects: {
      eyebrow: "Projets",
      title: "Projets techniques et cas d'etude",
      filters: [
        { key: "all", label: "Tous" },
        { key: "electronics", label: "Electronique" },
        { key: "drones", label: "Drones" },
        { key: "cad", label: "CAO" },
        { key: "cnc", label: "Fraisage CNC" },
        { key: "3d-printing", label: "Impression 3D" },
        { key: "personal-rd", label: "R&D personnelle" },
      ],
      items: [
        {
          slug: "embedded-electronics-prototype",
          title: "Prototype electronique embarque",
          category: "Electronique",
          filter: "electronics",
          summary:
            "Projet provisoire pour un prototype electronique ou embarque. Remplacer par le perimetre verifie, les composants, les contraintes et les resultats de test.",
          tools: ["Microcontroleur", "Capteurs", "Equipement de test", "Documentation technique"],
          status: "A completer",
          subtitle: "Prototype electronique et systemes embarques",
          details: {
            context: "A completer.",
            objective: "A completer.",
            approach: "A completer.",
            result: "A completer.",
            skills: ["Electronique", "Systemes embarques", "Diagnostic", "Documentation"],
          },
        },
        {
          slug: "cad-digital-fabrication-study",
          title: "Etude CAO et fabrication numerique",
          category: "CAO",
          filter: "cad",
          summary:
            "Projet provisoire pour une conception mecanique, une impression 3D ou un workflow CNC. Remplacer par les modeles, materiaux, tolerances et sorties de fabrication.",
          tools: ["CAO", "Impression 3D", "Workflow CNC", "Mesure"],
          status: "A completer",
          subtitle: "Conception mecanique et workflow de fabrication",
          details: {
            context: "A completer.",
            objective: "A completer.",
            approach: "A completer.",
            result: "A completer.",
            skills: ["CAO", "Conception pour fabrication", "Iteration prototype", "Documentation technique"],
          },
        },
      ],
    },
    education: {
      eyebrow: "Formation & Certifications",
      title: "Diplomes, cours et certifications",
      groups: [
        {
          title: "Diplomes",
          items: [
            {
              name: "A completer",
              organization: "Organisation : A completer",
              year: "Annee : A completer",
              location: "Localisation : A completer",
              competencies: "Competences acquises : A completer",
            },
          ],
        },
        {
          title: "Cours",
          items: [
            {
              name: "A completer",
              organization: "Organisation : A completer",
              year: "Annee : A completer",
              location: "Localisation : A completer",
              competencies: "Competences acquises : A completer",
            },
          ],
        },
        {
          title: "Certifications",
          items: [
            {
              name: "A completer",
              organization: "Organisation : A completer",
              year: "Annee : A completer",
              location: "Localisation : A completer",
              competencies: "Competences acquises : A completer",
            },
          ],
        },
      ],
    },
    contact: {
      eyebrow: "Contact",
      title: "Disponible pour des projets techniques, stages, collaborations ou opportunites professionnelles.",
      location: "France - Bordeaux / Ardeche",
      email: "A completer",
      phone: "A completer",
      linkedin: "A completer",
      github: "https://github.com/levlevinov",
      websites: ["A completer"],
    },
    footer: {
      label: "Electronique, systemes embarques, CAO et fabrication numerique",
      copyright: "Copyright 2026 Lev Levinov",
    },
  },
};
